# Generated by Django 3.2 on 2022-09-11 14:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0026_alter_contest_business_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone Number should be digits of 11 characters e.g. 08100550044', regex='^0\\d{10}$')])),
                ('ref_shortcode', models.CharField(blank=True, max_length=15, unique=True)),
                ('guest_count', models.PositiveIntegerField(blank=True, null=True)),
                ('business_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_contest', to='auth_app.contest')),
            ],
            options={
                'ordering': ('-id',),
                'unique_together': {('business_owner', 'refer_name', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('guest_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone Number should be digits of 11 characters e.g. 08100550044', regex='^0\\d{10}$')])),
                ('business_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_guest', to='auth_app.contest')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_referral', to='base_app.referral')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
