# Generated by Django 3.2 on 2022-01-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='refer_message',
            field=models.CharField(default='Hello, i just signed up as a referral in your Referral Context, My name is ', max_length=100),
        ),
    ]
