# Generated by Django 3.2 on 2022-01-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_auto_20220120_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessOwner',
        ),
    ]
