# Generated by Django 3.2 on 2022-01-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0008_alter_referral_refer_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="ref_shortcode",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
