# Generated by Django 3.2 on 2022-01-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0009_alter_referral_ref_shortcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="refer_message",
            field=models.TextField(
                default="Hello, i am currently participating in a referral contest, kindly vote for me using this link "
            ),
        ),
    ]
