# Generated by Django 3.2 on 2022-02-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0019_auto_20220213_1352"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="guest_message",
        ),
    ]
