# Generated by Django 3.2 on 2022-02-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0021_auto_20220220_0317"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guest",
            old_name="contest",
            new_name="business_name",
        ),
    ]
