# Generated by Django 3.2 on 2022-02-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_alter_contest_starting_date'),
        ('base_app', '0022_rename_contest_guest_business_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='business_name',
            new_name='business_owner',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='business_contest',
            new_name='business_owner',
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('business_owner', 'refer_name', 'phone_number')},
        ),
    ]
