# Generated by Django 3.2 on 2022-02-24 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0023_auto_20220220_2045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="ip",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone Number should be digits of 11 characters e.g. 08100550044",
                        regex="^0\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone Number should be digits of 11 characters e.g. 08100550044",
                        regex="^0\\d{10}$",
                    )
                ],
            ),
        ),
    ]
