# Generated by Django 3.2 on 2022-03-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0024_auto_20220224_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='guest_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
