# Generated by Django 3.2 on 2022-03-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0025_referral_guest_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='guest',
            name='guest_count',
        ),
    ]
