# Generated by Django 3.2 on 2022-01-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessowner",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
