# Generated by Django 3.2 on 2022-01-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20220120_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner',
            name='business_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
