# Generated by Django 3.2 on 2022-01-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_businessowner_business_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner',
            name='reward_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Product', 'Product')], default='Cash', max_length=20),
        ),
    ]
