# Generated by Django 3.2 on 2022-01-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0005_businessowner_reward_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessowner",
            name="is_business_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="businessowner",
            name="is_referral",
            field=models.BooleanField(default=False),
        ),
    ]
