# Generated by Django 3.2 on 2022-02-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0007_auto_20220203_0937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessowner",
            name="business_name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="business name"
            ),
        ),
    ]
