# Generated by Django 3.2 on 2022-02-07 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_businessowner_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='cash_price',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number should be in the format: 2348105506606', regex='^234\\d{10}$')]),
        ),
    ]
