# Generated by Django 3.2 on 2022-02-13 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_auto_20220207_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number should be in the format: 2348105506606', regex='^0\\d{10}$')]),
        ),
    ]
