# Generated by Django 3.2 on 2022-02-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_businessowner_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessowner',
            name='is_business_owner',
        ),
        migrations.RemoveField(
            model_name='businessowner',
            name='is_referral',
        ),
    ]
