# Generated by Django 3.2 on 2022-02-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0013_auto_20220220_0137"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contest",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterField(
            model_name="contest",
            name="ending_date",
            field=models.DateTimeField(blank=True),
        ),
    ]
