# Generated by Django 3.2 on 2022-02-20 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0014_auto_20220220_0317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="starting_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
