# Generated by Django 3.2 on 2022-09-10 10:13

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0020_contest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='business_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number should be in the format: 08105506606', regex='^0\\d{10}$')]),
        ),
    ]
