# Generated by Django 3.2 on 2022-09-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_auto_20220910_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='unique_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
