# Generated by Django 3.2 on 2022-09-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0022_alter_contest_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='business_name',
            field=models.CharField(max_length=150, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='shortcode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
