# Generated by Django 3.2 on 2022-09-11 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0024_auto_20220911_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='business_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
