# Generated by Django 3.2 on 2022-09-11 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_alter_contest_business_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='business_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
