# Generated by Django 3.2 on 2022-09-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_alter_contest_business_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='referral_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
